export const showrooms = [
  {
    id: 1,
    slug: 'first',
    city: 'г. Запорожье',
    street: 'проспект Соборный 83/85, 69000',
    location: 'ТРЦ "Аврора"',
    floor: '2',
    phone: '056 787 07 96',
    worktime: [10, 20],
    weekends: [],
    imgs: ['/imgs/shop1.png'],
  },
  {
    id: 2,
    slug: 'second',
    city: 'г. Запорожье',
    street: 'проспект Соборный 109б, 69000',
    location: 'ТРЦ "PANORAMA"',
    floor: '1',
    phone: '056 787 07 96',
    worktime: [10, 20],
    weekends: [],
    imgs: ['/imgs/shop1.png'],
  },
]
